Nvhlession03View/Nvhlession03View/Models/ErrorViewModels.cs
namespace Nvhlession03View.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Nvhlession03View/Nvhlession03View/Models/category.cs
namespace Nvhlession03View.Models
{
    public class category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Nvhlession03View/Nvhlession03View/Controllers/NvhHomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Nvhlession03View.Models;

namespace Nvhlession03View.Controllers
{
    public class NvhHomeController : Controller
    {
        private readonly ILogger<NvhHomeController> _logger;

        public NvhHomeController(ILogger<NvhHomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult NvhIndex()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult NvhAbout()
        {
            return View();
        }

        public IActionResult NvhViewIf()
        {
            return View();
        }
        public IActionResult NvhViewLoop()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Nvhlession03View/Nvhlession03View/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Nvhlession03View.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Nvhlession03View/Nvhlession03View/Pages/NvhIndex.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Nvhlession03View.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Nvhlession03View/Nvhlession03View/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Nvhlession03View.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }

}

Nvhlession03View/Nvhlession03View/Pages/Shared/_NvhFooter.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Nvhlession03View.Pages.Shared
{
    public class _NvhFooterModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Nvhlession03View/Nvhlession03View/Pages/Shared/_NvhLeftMenu.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Nvhlession03View.Pages.Shared
{
    public class _NvhLeftMenuModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Nvhlession03View/Nvhlession03View/Pages/Shared/_NvhNavbar.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Nvhlession03View.Pages.Shared
{
    public class _NvhNavbarModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Nvhlession03View/Nvhlession03View/ViewComponents/NvhDemoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Nvhlession03View.Models;
using System.Collections.Generic;


namespace Nvhlession03View.ViewComponents
{
    public class TvcDemoViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            List<category> categories = new List<category>()
            {
                new category {Id=1,Name="Điện tử" },
                new category {Id=2,Name="Điện Lạnh"},

                new category {Id=3,Name="Đồ gia dụng"},
                new category {Id=4,Name="Tiện ích"},
            };
            return View(categories);
        }
    }
}

Nvhlession03View/Nvhlession03View/Pages/NvhIndex.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Nvhlession03View/Nvhlession03View/Pages/Shared/Components/NvhDemo/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Nvhlession03View/Nvhlession03View/Pages/Shared/NvhHome/NvhAbout.cshtml
@{
    ViewData["Title"] = "Thông tin sinh viên";
}

<div class="alert alert-info">
    <h1>@ViewData["Title"]</h1>
    <hr />
    <p>Mã sinh viên: 2210900031</p>
    <p>Họ và tên: Nguyễn Văn Huỳnh</p>
    <p>Lớp: K22CNT3</p>
    <p>Email:huynhnguyen@gmail.com</p>
    <p>
        Điện thoại:
        <a href="tel:0911237896">0911 237 896</a>
    </p>
</div>

Nvhlession03View/Nvhlession03View/Pages/Shared/NvhHome/NvhViewLoop.cshtml
@{
    ViewData["Title"] = "Cấu trúc lặp";
}

<h1>@ViewData["Title"]</h1>
<hr />
@{
    for (int i = 0; i < 10; i++)
    {
        if (i % 2 == 0)
        {
            <span class="alert alert-danger">@i</span>
        }
        else
        {
            <span class="alert alert-success">@i</span>
        }
    }
}

Nvhlession03View/Nvhlession03View/Pages/Shared/NvhHome/Nvhviewlf.cshtml
@{
    ViewData["Title"] = "Câu trúc điều khiển if";

    var total = 123123;
}

<h1>@ViewData["Title"]</h1>
<hr />
<h3>Total $: @total</h3>
@if (total > 5000)
{
    <p>Bạn là người giàu</p>
}
else
{
    <p>Bạn là người chưa giàu</p>
}
<hr />
@{
    int score = 85;
}

@if (score >= 90)
{
    <p>Xuất sắc!</p>
}
else if (score >= 75)
{
    <p>Khá giỏi!</p>
}
else
{
    <p>Cần cố gắng hơn.</p>
}

Nvhlession03View/Nvhlession03View/Pages/Shared/_NvhFooter.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - Nvhlession03View - <a asp-area="" asp-controller="NvhHome" asp-action="NvhAbout">Thông tin</a>
    </div>

    <div class="col-3">
        @await Component.InvokeAsync("NvhDemo")
    </div>
</footer>

Nvhlession03View/Nvhlession03View/Pages/Shared/_NvhLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nvhlession03View</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Nvhlession03View.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <partial name="_NvhNavBar" />
    </header>
    <div class="container">
        <div class="row">
            <div class="col-3">
                <partial name="_NvhLeftMenu" />
            </div>
            <main role="main" class="pb-3 col-6">
                @RenderBody()
            </main>
            <div class="col-3">
                @await Component.InvokeAsync("NvhDemo")
            </div>
        </div>
    </div>

    <partial name="_NvhFooter" />


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Nvhlession03View/Nvhlession03View/Pages/Shared/_NvhLeftMenu.cshtml
<ul class="list-group">
    <li class="list-group-item active" aria-current="true">DANH MỤC</li>
    <li class="list-group-item">A second item</li>
    <li class="list-group-item">A third item</li>
    <li class="list-group-item">A fourth item</li>
    <li class="list-group-item">And a fifth one</li>
</ul>

Nvhlession03View/Nvhlession03View/Pages/Shared/_NvhNavbar.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="NvhHome" asp-action="Index">Nvhlession03View</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area=""  asp-action="NvhIndex">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area=""  asp-action="Privacy">Privacy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="NvhHome" asp-action="NvhAbout">Thông tin sinh viên</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="NvhHome" asp-action="NvhViewIf">View If</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="NvhHome" asp-action="NVhViewLoop">View Loop</a>
                </li>
            </ul>
        </div>
    </div>
</nav>